Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you
might choose one over the other.

In [ ]:
Ans 1:-
Ordinal Encoding and Label Encoding are both techniques used to convert categorical data into numerical format, but they differ in their approach and application.

In [ ]:
Ordinal Encoding:
    Ordinal Encoding is used when the categorical data has a natural order or ranking among its categories.
    It assigns numerical values to the categories based on their order, preserving the ordinal relationship between the categories.
    The assigned numerical values can be any integers, and the order matters in the context of the data.
    
Example: Educational Level
    Suppose we have a dataset containing the "Educational Level" feature with categories: "High School," "Associate Degree," "Bachelor's Degree," "Master's Degree,"
    and "Ph.D." In this case, we can use Ordinal Encoding to assign numerical values 1, 2, 3, 4, and 5 to the respective categories, maintaining the meaningful order
    of educational levels.

In [ ]:
Label Encoding:
    Label Encoding is used when the categorical data does not have any inherent order or ranking among its categories.
    It assigns unique numerical labels (integers) to each category, starting from 0 or 1.
    The numerical values have no mathematical significance and do not imply any specific order among the categories.
    
Example: Colors
    Suppose we have a dataset containing the "Color" feature with categories: "Red," "Blue," "Green," "Yellow," and "Purple."
    In this case, we can use Label Encoding to assign numerical labels 0, 1, 2, 3, and 4 to the respective colors.

In [ ]:
When to choose one over the other:
    Choose Ordinal Encoding when the categorical data has a natural order or ranking among the categories, and you want to preserve that order in the numerical
    representation.
    Choose Label Encoding when the categorical data does not have any inherent order, and you only need unique numerical labels for identification purposes.

Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in
a machine learning project.

In [ ]:
Ans 2:-
Target Guided Ordinal Encoding is a feature encoding technique that is specifically used for categorical variables in the context of supervised machine learning
projects.
It combines the benefits of ordinal encoding with the target variables information to create a meaningful and informative numerical representation of the categorical
data.

In [ ]:
The steps involved in Target Guided Ordinal Encoding are as follows:
    Calculate the mean of the target variable for each category in the categorical feature.
    Order the categories based on the calculated means.
    Assign a numerical value to each category, with lower values for categories with lower means (indicating a lower likelihood of the target outcome) and higher
    values for categories with higher means (indicating a higher likelihood of the target outcome).

In [ ]:
Calculate the mean of the target variable "Churn" for each contract type category:
    Mean of "Churn" for "Monthly" contracts = 0.30 (30% churn rate for monthly contracts)
    Mean of "Churn" for "One Year" contracts = 0.15 (15% churn rate for one-year contracts)
    Mean of "Churn" for "Two Year" contracts = 0.05 (5% churn rate for two-year contracts)
    
Order the categories based on the calculated means:
    "Two Year" contracts have the lowest churn rate (0.05), so they are assigned the lowest numerical value, say 1.
    "One Year" contracts have a higher churn rate (0.15), so they are assigned a higher numerical value, say 2.
    "Monthly" contracts have the highest churn rate (0.30), so they are assigned the highest numerical value, say 3.

Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated?

In [ ]:
Ans 3:-
Covariance is a statistical measure that quantifies the degree to which two random variables change together.
It measures the joint variability or co-movement between two variables and indicates the direction of their relationship (positive or negative) and the strength of
their association.

In [ ]:
Importance of Covariance in Statistical Analysis:
Covariance is essential in statistical analysis for several reasons:
    
Relationship between Variables:
    Covariance helps to understand the relationship between two variables.
    A positive covariance indicates that as one variable increases, the other tends to increase, and a negative covariance indicates that as one variable increases,
    the other tends to decrease.

Portfolio Diversification:
    In finance, covariance is crucial in building diversified investment portfolios.
    It helps to measure how different assets returns move in relation to each other,which allows investors to assess the risk and potential benefits of combining
    assets in a portfolio.

Multivariate Analysis:
    Covariance is used in multivariate analysis to study the relationships between multiple variables simultaneously.
    It provides insights into how different variables are related to each other in a dataset.

Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium,
large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library.
Show your code and explain the output.

In [2]:
# Ans 4:-
from sklearn.preprocessing import LabelEncoder

colors = ['red', 'green', 'blue', 'red', 'blue']
sizes = ['small', 'medium', 'large', 'medium', 'small']
materials = ['wood', 'metal', 'plastic', 'plastic', 'metal']

label_encoder = LabelEncoder()

encoded_colors = label_encoder.fit_transform(colors)
encoded_sizes = label_encoder.fit_transform(sizes)
encoded_materials = label_encoder.fit_transform(materials)

print("Encoded Colors:", encoded_colors)
print("Encoded Sizes:", encoded_sizes)
print("Encoded Materials:", encoded_materials)


Encoded Colors: [2 1 0 2 0]
Encoded Sizes: [2 1 0 1 2]
Encoded Materials: [2 0 1 1 0]


Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education
level. Interpret the results.

In [3]:
# Ans 5:-
import numpy as np

age = [25, 30, 35, 40, 45]
income = [50000, 60000, 70000, 80000, 90000]
education = [12, 16, 14, 18, 15]

data = np.array([age, income, education])

cov_matrix = np.cov(data)

print("Covariance Matrix:")
print(cov_matrix)


Covariance Matrix:
[[6.25e+01 1.25e+05 1.00e+01]
 [1.25e+05 2.50e+08 2.00e+04]
 [1.00e+01 2.00e+04 5.00e+00]]


In [ ]:
Interpretation:
    The covariance matrix shows the covariance values between each pair of variables.
    Each element (i, j) in the matrix represents the covariance between variable i and variable j.

Q6. You are working on a machine learning project with a dataset containing several categorical
variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD),
and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for
each variable, and why?

In [5]:
# Ans 6:-
from sklearn.preprocessing import LabelEncoder

gender = ['Male', 'Female']

label_encoder = LabelEncoder()
encoded_gender = label_encoder.fit_transform(gender)
print("Encoded Gender:", encoded_gender)

education_level = ['High School', "Bachelor's", "Master's", 'PhD']

ordinal_encoder = LabelEncoder()
encoded_education_level = ordinal_encoder.fit_transform(education_level)
print("Encoded Education Level:", encoded_education_level)

import pandas as pd

employment_status = ['Unemployed', 'Part-Time', 'Full-Time']
encoded_employment_status = pd.get_dummies(employment_status)
print("Encoded Employment Status:")
print(encoded_employment_status)


Encoded Gender: [1 0]
Encoded Education Level: [1 0 2 3]
Encoded Employment Status:
   Full-Time  Part-Time  Unemployed
0          0          0           1
1          0          1           0
2          1          0           0


Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two
categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/
East/West). Calculate the covariance between each pair of variables and interpret the results.

In [ ]:
Ans 7:-
To calculate the covariance between each pair of variables in the dataset, we first need the data for the "Temperature," "Humidity," "Weather Condition," and
"Wind Direction" variables.
Since I don't have the actual data, I'll provide a general explanation of how to interpret the covariance results

In [ ]:
Suppose we have a dataset with the following variables:

Temperature: [25, 30, 35, 40, 45]
Humidity: [40, 50, 60, 70, 80]
Weather Condition: ["Sunny", "Cloudy", "Rainy", "Sunny", "Rainy"]
Wind Direction: ["North", "South", "East", "West", "West"]

In [6]:
import numpy as np

temperature = np.array([25, 30, 35, 40, 45])
humidity = np.array([40, 50, 60, 70, 80])

covariance = np.cov(temperature, humidity)[0, 1]

print("Covariance between Temperature and Humidity:", covariance)



Covariance between Temperature and Humidity: 125.0
