In [1]:
import numpy as np

In [3]:
arr = np.array([3,4,6,2,5,6,5,3,4,3,3,456,867,3,76,2325,65])

In [4]:
np.short(arr)

array([   3,    4,    6,    2,    5,    6,    5,    3,    4,    3,    3,
        456,  867,    3,   76, 2325,   65], dtype=int16)

In [5]:
np.searchsorted(arr,34)

14

In [6]:
arr1 = np.array([23,45,56,5,6,45,34,0,0,0,54,54,64])

In [7]:
arr1

array([23, 45, 56,  5,  6, 45, 34,  0,  0,  0, 54, 54, 64])

In [8]:
np.count_nonzero(arr1)

10

In [9]:
np.where(arr1 >6)

(array([ 0,  1,  2,  5,  6, 10, 11, 12]),)

In [14]:
np.extract(arr >3,arr)

array([   4,    6,    5,    6,    5,    4,  456,  867,   76, 2325,   65])

In [15]:
arr

array([   3,    4,    6,    2,    5,    6,    5,    3,    4,    3,    3,
        456,  867,    3,   76, 2325,   65])

In [16]:
arr.byteswap()

array([  216172782113783808,   288230376151711744,   432345564227567616,
         144115188075855872,   360287970189639680,   432345564227567616,
         360287970189639680,   216172782113783808,   288230376151711744,
         216172782113783808,   216172782113783808, -4034943791147253760,
        7134546234684997632,   216172782113783808,  5476377146882523136,
        1515742749586882560,  4683743612465315840])

In [17]:
a = np.copy(arr)

In [19]:
a

array([   3,    4,    6,    2,    5,    6,    5,    3,    4,    3,    3,
        456,  867,    3,   76, 2325,   65])

In [21]:
b = arr.view()

In [23]:
b[0] = 30

In [24]:
b

array([  30,    4,    6,    2,    5,    6,    5,    3,    4,    3,    3,
        456,  867,    3,   76, 2325,   65])

In [25]:
a

array([   3,    4,    6,    2,    5,    6,    5,    3,    4,    3,    3,
        456,  867,    3,   76, 2325,   65])

In [26]:
arr

array([  30,    4,    6,    2,    5,    6,    5,    3,    4,    3,    3,
        456,  867,    3,   76, 2325,   65])

In [27]:
import numpy.matlib as nm

In [31]:
nm.zeros((3,4))

matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
nm.eye(3)

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [36]:
arr1 = np.random.randint([[3,4],[4,5]])
arr2 = np.random.randint([[3,4],[4,5]])

In [37]:
arr1

array([[0, 2],
       [3, 4]])

In [38]:
arr2

array([[0, 1],
       [2, 0]])

In [39]:
np.dot(arr1,arr2)

array([[4, 0],
       [8, 3]])

In [40]:
arr1@arr2

array([[4, 0],
       [8, 3]])