In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
ar = np.array(l)

In [4]:
ar

array([1, 2, 3, 4, 5])

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray (l)

array([1, 2, 3, 4, 5])

In [8]:
a = [1,2,3]

In [9]:
np.asanyarray(a)

array([1, 2, 3])

In [10]:
b = np.matrix(l)

In [11]:
b

matrix([[1, 2, 3, 4, 5]])

In [12]:
np.asanyarray(b)

matrix([[1, 2, 3, 4, 5]])

In [13]:
a = np.array(l)

In [14]:
a

array([1, 2, 3, 4, 5])

In [15]:
c=a

In [16]:
c

array([1, 2, 3, 4, 5])

In [17]:
a

array([1, 2, 3, 4, 5])

In [18]:
c[0]=100

In [19]:
c

array([100,   2,   3,   4,   5])

In [20]:
a

array([100,   2,   3,   4,   5])

In [21]:
d = np.copy(a)

In [22]:
d

array([100,   2,   3,   4,   5])

In [23]:
a

array([100,   2,   3,   4,   5])

In [24]:
a[1]= 400

In [25]:
a

array([100, 400,   3,   4,   5])

In [26]:
d

array([100,   2,   3,   4,   5])

In [27]:
np.fromfunction(lambda i,j:i == j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
np.fromfunction(lambda i,j:i * j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [29]:
iterable = (i*i for i in range (5))

In [30]:
np.fromiter(iterable,float)


array([ 0.,  1.,  4.,  9., 16.])

In [31]:
np.fromstring('135,3345',sep= ',')

array([ 135., 3345.])

In [32]:
l = [1,2,3,4,5,6]

In [33]:
ar =np.array(l)

In [34]:
ar.ndim

1

In [35]:
ar2 = np.array([[1,2,3,4],[5,6,7,8]])

In [36]:
ar2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
ar2.ndim

2

In [38]:
ar.size

6

In [39]:
ar2.size

8

In [40]:
ar.shape

(6,)

In [41]:
ar2.shape

(2, 4)

In [42]:
ar.dtype

dtype('int64')

In [43]:
ar2.dtype

dtype('int64')

In [44]:
ar22 = np.array([(1,1.5,45,4) , (25,5,45,66)])

In [45]:
ar22

array([[ 1. ,  1.5, 45. ,  4. ],
       [25. ,  5. , 45. , 66. ]])

In [46]:
ar22.dtype

dtype('float64')

In [47]:
list(range(5))

[0, 1, 2, 3, 4]

In [48]:
list(np.arange(2.3,5.6,1.1))

[2.3, 3.4, 4.5]

In [49]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [50]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [51]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [53]:
ar4 = np.zeros((4,3,2,4))

In [54]:
ar4.ndim

4

In [55]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
on = np.ones((2,3,2))

In [57]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [58]:
on*5

array([[[5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.]]])

In [59]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [60]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [62]:
np.logspace(2,3,13,base=2)

array([4.        , 4.23785238, 4.48984819, 4.75682846, 5.0396842 ,
       5.33935942, 5.65685425, 5.99322831, 6.34960421, 6.72717132,
       7.12718975, 7.5509945 , 8.        ])

In [63]:
arr =np.random.randn(3,2)

In [64]:
import pandas as pd

In [65]:
pd.DataFrame(arr)

0         1
0 -0.837752 -2.188186
1 -0.493432  0.773785
2  3.362761  1.486508

In [66]:
np.random.rand(2,4)

array([[0.76471225, 0.09877772, 0.64935442, 0.66116433],
       [0.36786874, 0.2138725 , 0.28912961, 0.93028298]])

In [67]:
np.random.randint(1,110,(3,4))

array([[95, 23,  6, 50],
       [13, 13, 72, 91],
       [43, 88, 24, 45]])

In [68]:
arr = np.random.rand(5,3)

In [69]:
arr

array([[0.63695566, 0.26679553, 0.05873301],
       [0.9153133 , 0.97350613, 0.27479385],
       [0.84648344, 0.31540923, 0.91129733],
       [0.89813793, 0.21994933, 0.60856004],
       [0.57098569, 0.31785262, 0.72106674]])

In [70]:
arr.reshape(5,3)

array([[0.63695566, 0.26679553, 0.05873301],
       [0.9153133 , 0.97350613, 0.27479385],
       [0.84648344, 0.31540923, 0.91129733],
       [0.89813793, 0.21994933, 0.60856004],
       [0.57098569, 0.31785262, 0.72106674]])

In [71]:
arr

array([[0.63695566, 0.26679553, 0.05873301],
       [0.9153133 , 0.97350613, 0.27479385],
       [0.84648344, 0.31540923, 0.91129733],
       [0.89813793, 0.21994933, 0.60856004],
       [0.57098569, 0.31785262, 0.72106674]])

In [72]:
arr[1][1]

0.9735061344909678

In [73]:
arr[1:3,2]

array([0.27479385, 0.91129733])

In [74]:
arr2 = np.random.randint(1,100,(4,4))

In [75]:
arr2[arr2>50]

array([73, 95, 84, 93, 59, 96, 77])

In [76]:
arr2

array([[ 9, 73,  5, 95],
       [31, 84,  9, 93],
       [14, 59, 17, 34],
       [42, 45, 96, 77]])

In [77]:
arr2[1:3,[1,2]]

array([[84,  9],
       [59, 17]])

In [78]:
arr2[1][1] = 600

In [79]:
arr2

array([[  9,  73,   5,  95],
       [ 31, 600,   9,  93],
       [ 14,  59,  17,  34],
       [ 42,  45,  96,  77]])

In [80]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [81]:
arr1

array([[1, 1, 2],
       [2, 2, 1],
       [1, 1, 2]])

In [82]:
arr2

array([[1, 1, 1],
       [1, 2, 1],
       [1, 2, 1]])

In [83]:
arr1 + arr2

array([[2, 2, 3],
       [3, 4, 2],
       [2, 3, 3]])

In [84]:
arr1 / arr2

array([[1. , 1. , 2. ],
       [2. , 1. , 1. ],
       [1. , 0.5, 2. ]])

In [85]:
arr1 - arr2

array([[ 0,  0,  1],
       [ 1,  0,  0],
       [ 0, -1,  1]])

In [86]:
arr1 * arr2

array([[1, 1, 2],
       [2, 4, 1],
       [1, 2, 2]])

In [87]:
arr1 @ arr2

array([[4, 7, 4],
       [5, 8, 5],
       [4, 7, 4]])

In [88]:
arr1/0

/tmp/ipykernel_1638/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [89]:
arr1+100

array([[101, 101, 102],
       [102, 102, 101],
       [101, 101, 102]])

In [90]:
arr1**2

array([[1, 1, 4],
       [4, 4, 1],
       [1, 1, 4]])

In [92]:
arr = np.zeros((4,4))

In [93]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [107]:
row1 = np.array([[1,2,3,4]])

In [102]:
row1

array([1, 2, 3, 4])

In [104]:
arr+row1

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [108]:
row1.T

array([[1],
       [2],
       [3],
       [4]])

In [109]:
row1+arr

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [110]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [113]:
arr3 = np.random.randint(1,4,(4,5))

In [114]:
np.sqrt(arr3)

array([[1.41421356, 1.41421356, 1.        , 1.41421356, 1.41421356],
       [1.41421356, 1.        , 1.73205081, 1.41421356, 1.        ],
       [1.73205081, 1.41421356, 1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.41421356, 1.        , 1.        ]])

In [115]:
arr3

array([[2, 2, 1, 2, 2],
       [2, 1, 3, 2, 1],
       [3, 2, 2, 1, 2],
       [2, 2, 2, 1, 1]])

In [116]:
np.exp(arr3)

array([[ 7.3890561 ,  7.3890561 ,  2.71828183,  7.3890561 ,  7.3890561 ],
       [ 7.3890561 ,  2.71828183, 20.08553692,  7.3890561 ,  2.71828183],
       [20.08553692,  7.3890561 ,  7.3890561 ,  2.71828183,  7.3890561 ],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ,  2.71828183,  2.71828183]])

In [117]:
np.log10(arr3)

array([[0.30103   , 0.30103   , 0.        , 0.30103   , 0.30103   ],
       [0.30103   , 0.        , 0.47712125, 0.30103   , 0.        ],
       [0.47712125, 0.30103   , 0.30103   , 0.        , 0.30103   ],
       [0.30103   , 0.30103   , 0.30103   , 0.        , 0.        ]])