In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,4))

In [3]:
arr

array([[5, 4, 2, 5],
       [3, 2, 8, 7],
       [4, 2, 3, 9]])

In [4]:
arr.reshape(6,2)

array([[5, 4],
       [2, 5],
       [3, 2],
       [8, 7],
       [4, 2],
       [3, 9]])

In [5]:
arr.reshape(2,6)

array([[5, 4, 2, 5, 3, 2],
       [8, 7, 4, 2, 3, 9]])

In [6]:
arr.T

array([[5, 3, 4],
       [4, 2, 2],
       [2, 8, 3],
       [5, 7, 9]])

In [7]:
arr.flatten()

array([5, 4, 2, 5, 3, 2, 8, 7, 4, 2, 3, 9])

In [8]:
arr1 = np.array([1,2,3,4,5])

In [9]:
arr1.ndim

1

In [10]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [11]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4, 5]])

In [12]:
arr

array([[5, 4, 2, 5],
       [3, 2, 8, 7],
       [4, 2, 3, 9]])

In [13]:
np.squeeze(arr)

array([[5, 4, 2, 5],
       [3, 2, 8, 7],
       [4, 2, 3, 9]])

In [14]:
data = np.array([[1],[2],[3]])

In [15]:
data

array([[1],
       [2],
       [3]])

In [16]:
np.squeeze(data)

array([1, 2, 3])

In [17]:
arr1

array([1, 2, 3, 4, 5])

In [18]:
np.repeat(arr1,2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [19]:
np.roll(arr1,3)

array([3, 4, 5, 1, 2])

In [21]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [23]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [25]:
arr1

array([[5, 6, 4, 1],
       [1, 1, 4, 3],
       [3, 6, 5, 3]])

In [26]:
arr2

array([[7, 7, 5, 9],
       [7, 8, 6, 2],
       [5, 4, 4, 4]])

In [27]:
arr1+arr2

array([[12, 13,  9, 10],
       [ 8,  9, 10,  5],
       [ 8, 10,  9,  7]])

In [28]:
arr1*arr2

array([[35, 42, 20,  9],
       [ 7,  8, 24,  6],
       [15, 24, 20, 12]])

In [29]:
arr1-arr2

array([[-2, -1, -1, -8],
       [-6, -7, -2,  1],
       [-2,  2,  1, -1]])

In [30]:
arr1/arr2

array([[0.71428571, 0.85714286, 0.8       , 0.11111111],
       [0.14285714, 0.125     , 0.66666667, 1.5       ],
       [0.6       , 1.5       , 1.25      , 0.75      ]])

In [31]:
arr1**arr2

array([[ 78125, 279936,   1024,      1],
       [     1,      1,   4096,      9],
       [   243,   1296,    625,     81]])

In [32]:
arr1%arr2

array([[5, 6, 4, 1],
       [1, 1, 4, 1],
       [3, 2, 1, 3]])

In [33]:
arr1&arr2

array([[5, 6, 4, 1],
       [1, 0, 4, 2],
       [1, 4, 4, 0]])

In [34]:
arr1|arr2

array([[7, 7, 5, 9],
       [7, 9, 6, 3],
       [7, 6, 5, 7]])

In [35]:
-arr1

array([[-5, -6, -4, -1],
       [-1, -1, -4, -3],
       [-3, -6, -5, -3]])

In [38]:
arr = np.array(['Gaurang',"Bhimani"])

In [39]:
arr

array(['Gaurang', 'Bhimani'], dtype='<U7')

In [40]:
np.char.upper(arr)

array(['GAURANG', 'BHIMANI'], dtype='<U7')

In [41]:
np.char.capitalize(arr)

array(['Gaurang', 'Bhimani'], dtype='<U7')

In [42]:
np.sin(arr1)

array([[-0.95892427, -0.2794155 , -0.7568025 ,  0.84147098],
       [ 0.84147098,  0.84147098, -0.7568025 ,  0.14112001],
       [ 0.14112001, -0.2794155 , -0.95892427,  0.14112001]])

In [43]:
np.cos(arr1)

array([[ 0.28366219,  0.96017029, -0.65364362,  0.54030231],
       [ 0.54030231,  0.54030231, -0.65364362, -0.9899925 ],
       [-0.9899925 ,  0.96017029,  0.28366219, -0.9899925 ]])

In [44]:
np.tan(arr1)

array([[-3.38051501, -0.29100619,  1.15782128,  1.55740772],
       [ 1.55740772,  1.55740772,  1.15782128, -0.14254654],
       [-0.14254654, -0.29100619, -3.38051501, -0.14254654]])

In [45]:
np.log(arr1)

array([[1.60943791, 1.79175947, 1.38629436, 0.        ],
       [0.        , 0.        , 1.38629436, 1.09861229],
       [1.09861229, 1.79175947, 1.60943791, 1.09861229]])

In [46]:
np.sqrt(arr1)

array([[2.23606798, 2.44948974, 2.        , 1.        ],
       [1.        , 1.        , 2.        , 1.73205081],
       [1.73205081, 2.44948974, 2.23606798, 1.73205081]])

In [48]:
np.power(arr1,2)

array([[25, 36, 16,  1],
       [ 1,  1, 16,  9],
       [ 9, 36, 25,  9]])

In [49]:
np.mean(arr1)

3.5

In [50]:
np.median(arr1)

3.5

In [51]:
np.min(arr1)

1

In [52]:
np.max(arr1)

6

In [54]:
np.var(arr1)

3.0833333333333335